### ISSUE TITLE
It's not work on my redmi k20 pro with HyperOS custom rom.

### ISSUE THREAD

**Issue by Dark-Official-007** [programminghoch10/MobileIconChanger#11]
It's not work on my redmi k20 pro with HyperOS custom rom. When I changed it from HyperCeiler to 6G it got changed but it is not getting changed with mobileiconchanger. I also flashed fake 5G icon modules but that too did not do anything.I have given 2 pictures, the first one is before restarting the system UI, the second one is after restarting the system UI.
![Screenshot_2024-09-22-04-24-20-772_com programminghoch10 mobileiconchanger](https://github.com/user-attachments/assets/1c194c0e-f4b7-47de-a17b-840938d0af1f)
![Screenshot_2024-09-22-04-24-46-648_com programminghoch10 mobileiconchanger](https://github.com/user-attachments/assets/3bf7a892-7f23-4a92-b366-098df6dd847c)
![Screenshot_2024-09-16-06-34-26-933_com android settings](https://github.com/user-attachments/assets/c31d4d87-90d2-4ac3-8e09-9e027c42c8b9)

**Comment by programminghoch10** [comment]
read the readme properly
